version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-typegoose-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: express-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
